bracketSameLine: true
bracketSpacing: true
printWidth: 140
quoteProps: as-needed
semi: true
singleQuote: false
trailingComma: es5
useTabs: true
htmlWhitespaceSensitivity: strict
arrowParens: avoid

# Add from Svelte
plugins:
  - prettier-plugin-svelte
  - prettier-plugin-css-order
overrides:
  - files: "*.svelte"
    options:
      parser: svelte
