bracketSameLine: true
bracketSpacing: true
printWidth: 100
quoteProps: as-needed
semi: true
singleQuote: false
trailingComma: es5
useTabs: false
htmlWhitespaceSensitivity: strict
arrowParens: always
endOfLine: "lf"

# Add from Svelte
plugins:
  - prettier-plugin-svelte
  - prettier-plugin-css-order
overrides:
  - files: "*.svelte"
    options:
      parser: svelte
